### ISSUE TITLE
cyrface on mac 

### ISSUE THREAD

**Issue by danciui** [saezlab/cyrface#1]
Hi,
I am trying to see if cytocopter would work for my project. It currently doesn't work at all because cyrface wants Rscript to be located in /usr/bin and that location is no longer available on Mac due to the new El Capitan security model. RScript is located in /usr/local/bin instead. (I get the following error "Error executing task: R executable /usr/bin/Rscript not found" when I try to cyrface plot). I think the path needs to be changed in two java files. Thanks!

**Comment by mschubert** [comment]
@EmanuelGoncalves, this looks like it could be an easy fix?

I'm not sure how Mac handles the environment, but on Linux I would use `/usr/bin/env Rscript` to account for whichever path is set up. This will still not work in Windows, however.

**Comment by gabora** [comment]
The new implementation of CytocoptR does not require the R backend.
